// <auto-generated />
#nullable enable
using System.ComponentModel;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace InvoiceDesk.Resources;

[EditorBrowsable(EditorBrowsableState.Advanced)]
public static class Strings
{
    private static readonly ResourceManager resourceMan = new("InvoiceDesk.Resources.Strings", typeof(Strings).Assembly);
    private static CultureInfo? resourceCulture;

    public static ResourceManager ResourceManager => resourceMan;

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    private static string Get([CallerMemberName] string? name = null)
    {
        return resourceMan.GetString(name!, resourceCulture) ?? name ?? string.Empty;
    }

    public static string AppTitle => Get();
    public static string CompanyLabel => Get();
    public static string LanguageLabel => Get();
    public static string NewDraft => Get();
    public static string Save => Get();
    public static string Issue => Get();
    public static string ExportPdf => Get();
    public static string DeleteInvoice => Get();
    public static string ManageCompanies => Get();
    public static string ManageCustomers => Get();
    public static string InvoiceList => Get();
    public static string Search => Get();
    public static string FromDate => Get();
    public static string ToDate => Get();
    public static string Customer => Get();
    public static string IssueDate => Get();
    public static string StatusLabel => Get();
    public static string InvoiceLanguageLabel => Get();
    public static string Currency => Get();
    public static string SubTotal => Get();
    public static string TaxTotal => Get();
    public static string Total => Get();
    public static string Notes => Get();
    public static string Lines => Get();
    public static string DescriptionLabel => Get();
    public static string QuantityLabel => Get();
    public static string UnitPriceLabel => Get();
    public static string TaxRateLabel => Get();
    public static string VatTypeLabel => Get();
    public static string AddLine => Get();
    public static string RemoveLine => Get();
    public static string StatusDraft => Get();
    public static string StatusIssued => Get();
    public static string StatusPaid => Get();
    public static string StatusCancelled => Get();
    public static string InvoiceNumber => Get();
    public static string PdfSubTotalLabel => Get();
    public static string PdfTaxTotalLabel => Get();
    public static string PdfGrandTotalLabel => Get();
    public static string PdfNotes => Get();
    public static string PdfVatSummary => Get();
    public static string PdfCompany => Get();
    public static string PdfCustomer => Get();
    public static string PdfInvoiceNumber => Get();
    public static string PdfIssueDate => Get();
    public static string PdfLegalReverseCharge => Get();
    public static string PdfLegalExport => Get();
    public static string PdfLegalVatExempt => Get();
    public static string VatTypeDomestic => Get();
    public static string VatTypeIntraEuReverseCharge => Get();
    public static string VatTypeExportOutsideEu => Get();
    public static string VatTypeExempt => Get();
    public static string MessageSelectCompanyCustomers => Get();
    public static string MessageDraftCreated => Get();
    public static string MessageSelectCustomer => Get();
    public static string MessageSaveDraftOnly => Get();
    public static string MessageInvoiceSaved => Get();
    public static string MessageInvoiceIssued => Get();
    public static string MessagePdfIssuedOnly => Get();
        public static string MessageExportingPdf => Get();
        public static string MessagePdfExported => Get();
    public static string MessageInvoiceDeleteConfirm => Get();
    public static string MessageInvoiceDeleted => Get();
    public static string MessageInvoiceDeleteFailed => Get();
    public static string MessageDeleteDraftOnly => Get();
    public static string MessageCompanyDeleteIssued => Get();
    public static string MessageCompanyDeleteFailed => Get();
    public static string MessageCustomerDeleteHasInvoices => Get();
    public static string MessageCustomerDeleteFailed => Get();
    public static string MessageCustomerSaved => Get();
    public static string MessageCompanySaved => Get();
    public static string NameLabel => Get();
    public static string VatLabel => Get();
    public static string EikLabel => Get();
    public static string CountryLabel => Get();
    public static string AddressLabel => Get();
    public static string EmailLabel => Get();
    public static string PhoneLabel => Get();
    public static string IbanLabel => Get();
    public static string BicLabel => Get();
    public static string PrefixLabel => Get();
    public static string NextNumberLabel => Get();
    public static string LogoLabel => Get();
    public static string Delete => Get();
    public static string Close => Get();
    public static string VatRegisteredLabel => Get();
}
